name:                haskala
version:             0.1.0.0
github:              "githubuser/haskala"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskala#readme>

dependencies:
- bookhound >= 0.1.9 && < 0.2
- optparse-applicative >= 0.17.0 && < 0.18
- directory-tree >= 0.12.1 && < 0.13
- fsnotify >= 0.3.0.1 && < 0.4
- filepath >= 1.4.2.2 && < 1.5
- directory >= 1.3.7.0 && < 1.4

- base >= 4.7 && < 5
- containers
- extra >= 1.7.10 && < 1.8
- utility-ht >= 0.0.16

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
# Syntax
- LambdaCase
- MultiWayIf
- TupleSections
- PostfixOperators

# Types
- RankNTypes
- ExplicitForAll
- ScopedTypeVariables
- LiberalTypeSynonyms
- InstanceSigs
- FunctionalDependencies

# Records
- DuplicateRecordFields
- NoFieldSelectors
- NamedFieldPuns
- RecordWildCards
- OverloadedRecordDot

# Type Classes
- ConstrainedClassMethods
- MultiParamTypeClasses
- FlexibleContexts
- FlexibleInstances

# Convenience
- ApplicativeDo
- ParallelListComp
- MonadComprehensions

# Type Level Programming
- GADTs
- TypeFamilies
- TypeFamilyDependencies
- DataKinds
- PolyKinds

# Deriving
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveGeneric
- GeneralizedNewtypeDeriving


library:
  source-dirs: src

executables:
  haskala-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskala
